import coreWebVitals from "eslint-config-next/core-web-vitals";

// Next 16 removed `next lint`, and ESLint 10 reads flat config only.
// eslint-config-next 16 already exports a flat config array, so it is spread
// in directly rather than bridged through @eslint/eslintrc.
const config = [
  {
    ignores: [
      ".next/**",
      "node_modules/**",
      "next-env.d.ts",
      // Generated by the shadcn CLI and refreshed by re-running it.
      "components/ui/**",
    ],
  },
  ...coreWebVitals,
];

export default config;
