// Content data. Extracted from the former components/constant/enum.ts,
// which held page copy rather than enums.

// GitHub profile, repositories and language stats.

import { Facebook, Globe, Instagram } from "lucide-react";

import { ContactInfo } from "./contact";
import { PDFLink } from "./profile";

export const GitHubInfo = {
  githubLink: "https://github.com/rafaswe",
  personalInfo: {
    imageUrl: "/images/personal.png",
    name: "Mahiya Rahman Rafa",
    userName: "rafaswe",
    tag: "A learner",
    followersCount: 4,
    followingCount: 4,
    address: "Nayanagar, Khilkhet",
    addressLink: "https://maps.app.goo.gl/91kS6KwVpTtX4nxt5",
    position: "Frontend Developer",
  },
  techStack: [
    { name: "html", logo: "/images/html.svg" },
    { name: "ES6", logo: "/images/es6.svg" },
    { name: "JavaSript", logo: "/images/JS.svg" },
    { name: "TypeScript", logo: "/images/TS.svg" },
    { name: "React", logo: "/images/react.svg" },
    { name: "NextJS", logo: "/images/next.svg" },
    { name: "CSS", logo: "/images/css.svg" },
    { name: "Sass", logo: "/images/scss.svg" },
    { name: "Tailwind", logo: "/images/tailwind.svg" },
    { name: "Bootstrap", logo: "/images/bootstrap.svg" },
    { name: "Zustand", logo: "/images/zustand.svg" },
    { name: "Redux/ReduxToolkit", logo: "/images/redux.svg" },
    { name: "Java", logo: "/images/java.svg" },
    { name: "Git/GitHub", logo: "/images/github.svg" },
    { name: "VS code", logo: "/images/vsCode.svg" },
    { name: "NetBeans", logo: "/images/netbeans.svg" },
    { name: "Intellij", logo: "/images/intellij.svg" },
    { name: "Adobe XD", logo: "/images/adobeXD.svg" },
    { name: "Figma", logo: "/images/figma.svg" },
    { name: "Netlify", logo: "/images/netlify.svg" },
    { name: "Canva", logo: "/images/canva.svg" },
  ],
  links: [
    {
      label: "🔭 All of my projects are available at",
      link: "https://github.com/rafaswe",
      tag: "https://github.com/rafaswe",
    },
    {
      label: "📝 I regularly write articles on",
      link: "https://medium.com/@rahmanmahiya99",
      tag: "https://medium.com/@rahmanmahiya99",
    },
    {
      label: "💬 Ask me about",
      link: "#",
      tag: "Javascript, TypeScript, React, NextJS, Tailwind, Bootstrap",
    },
    {
      label: "📫 How to reach me",
      link: "mailto:mahiyarahmanrafa@gmail.com",
      tag: "mahiyarahmanrafa@gmail.com",
    },
    {
      label: "⚡ Know about my experiences",
      link: PDFLink,
      tag: "https://drive.google.com",
    },
  ],
  socialLinks: [
    {
      icon: Globe,
      label: "LinkedIn",
      value: "LinkedIn",
      link: "https://bd.linkedin.com/in/mahiya-rahman-rafa",
    },
    {
      icon: Instagram,
      label: "Instagram",
      value: "Instagram",
      link: "https://www.instagram.com/mahiya_rahman_rafa/",
    },
    {
      icon: Facebook,
      label: "Facebook",
      value: "Facebook",
      link: "https://www.facebook.com/odhorajaman.sporshika",
    },
    ...ContactInfo,
  ],
  stats: {
    logs: [
      { label: "Total Stars Earned", count: 145 },
      { label: "Total Commits (2025)", count: 22450 },
      { label: "Total PRs", count: 1563 },
      { label: "Total Issues", count: 4512 },
      { label: "Contributed to (last year)", count: 41 },
    ],
    totalContribution: 359,
    gitOpenDays: "Apr 23, 2019",
  },
  repository: [
    {
      label: "E-Governance-Client-Side",
      subLabel: "Forked from tanveer-610/E-Governance-Client-Side",
      lang: [{ name: "JavaScript", colorCode: "#F1E05A" }],
      star: 15,
      commit: 7,
      tag: "Public",
      link: "https://github.com/rafaswe/E-Governance-Client-Side",
    },
    {
      label: "E-Governance-Server-Side",
      subLabel: "Forked from tanveer-610/E-Governance-Server-Side",
      lang: [{ name: "", colorCode: "" }],
      star: 16,
      commit: 8,
      tag: "Public",
      link: "https://github.com/rafaswe/E-Governance-Server-Side",
    },
    {
      label: "Deaffodil-Demo-website",
      subLabel: "A demo Website of Daffodil Internation University",
      lang: [{ name: "HTML", colorCode: "#E34C26" }],
      star: 20,
      commit: 12,
      tag: "Public",
      link: "https://github.com/rafaswe/Deaffodil-Demo-website",
    },
    {
      label: "SumashTech",
      subLabel: "Single page of Sumash Tech website",
      lang: [{ name: "HTML", colorCode: "#E34C26" }],
      star: 9,
      commit: 5,
      tag: "Public",
      link: "https://github.com/rafaswe/SumashTech",
    },
    {
      label: "",
      subLabel: "",
      lang: [{ name: "", colorCode: "" }],
      star: 15,
      commit: 7,
      tag: "",
      link: "",
    },
    {
      label: "mediCloud",
      subLabel: "Forked from tanveer-610/mediCloud",
      lang: [{ name: "PHP", colorCode: "#4F5D95" }],
      star: 5,
      commit: 10,
      tag: "Public",
      link: "https://github.com/rafaswe/mediCloud",
    },
    {
      label: "",
      subLabel: "",
      lang: [{ name: "", colorCode: "" }],
      star: 15,
      commit: 7,
      tag: "",
      link: "",
    },
    {
      label: "",
      subLabel: "",
      lang: [{ name: "", colorCode: "" }],
      star: 15,
      commit: 7,
      tag: "",
      link: "",
    },
    {
      label: "",
      subLabel: "",
      lang: [{ name: "", colorCode: "" }],
      star: 15,
      commit: 7,
      tag: "",
      link: "",
    },
    {
      label: "",
      subLabel: "",
      lang: [{ name: "", colorCode: "" }],
      star: 15,
      commit: 7,
      tag: "",
      link: "",
    },
    {
      label: "",
      subLabel: "",
      lang: [{ name: "", colorCode: "" }],
      star: 15,
      commit: 7,
      tag: "",
      link: "",
    },
    {
      label: "",
      subLabel: "",
      lang: [{ name: "", colorCode: "" }],
      star: 15,
      commit: 7,
      tag: "",
      link: "",
    },
    {
      label: "",
      subLabel: "",
      lang: [{ name: "", colorCode: "" }],
      star: 15,
      commit: 7,
      tag: "",
      link: "",
    },
    {
      label: "",
      subLabel: "",
      lang: [{ name: "", colorCode: "" }],
      star: 15,
      commit: 7,
      tag: "",
      link: "",
    },
    {
      label: "",
      subLabel: "",
      lang: [{ name: "", colorCode: "" }],
      star: 15,
      commit: 7,
      tag: "",
      link: "",
    },
    {
      label: "",
      subLabel: "",
      lang: [{ name: "", colorCode: "" }],
      star: 15,
      commit: 7,
      tag: "",
      link: "",
    },
    {
      label: "",
      subLabel: "",
      lang: [{ name: "", colorCode: "" }],
      star: 15,
      commit: 7,
      tag: "",
      link: "",
    },
    {
      label: "",
      subLabel: "",
      lang: [{ name: "", colorCode: "" }],
      star: 15,
      commit: 7,
      tag: "",
      link: "",
    },
    {
      label: "",
      subLabel: "",
      lang: [{ name: "", colorCode: "" }],
      star: 15,
      commit: 7,
      tag: "",
      link: "",
    },
    {
      label: "",
      subLabel: "",
      lang: [{ name: "", colorCode: "" }],
      star: 15,
      commit: 7,
      tag: "",
      link: "",
    },
    {
      label: "",
      subLabel: "",
      lang: [{ name: "", colorCode: "" }],
      star: 15,
      commit: 7,
      tag: "",
      link: "",
    },
  ],
};
