// Single `cn` entry point for the whole app.
//
// Backed by shadcn's compiled `cn` package (a drop-in clsx + tailwind-merge
// replacement). Re-exported through this module rather than imported directly
// so the app has exactly one import path for it — `components/ui/*` files
// generated by the shadcn CLI are rewritten to point here too.
export { cn } from "cn"
